[MeuDrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7pCA9_Y0zdY25o9qYWLYf4Y-rAftY1SYFc5V-VibUQqnGZjyCZ4VhBNFUD9jBmoUMGi3x2b65Synv5Ix7sPAo6GudPKRuPWFJVw6_MIIwNClEwg2qhHVSOCPo5labZMtvnObjbx-Iel7pQnkQSFQBjpm1PdmlqmuAKuw4OyTkufmAszYdPDcjTJB4N9vPSBbMR9x0aCgYKAWYSARMSFQHGX2MiwzR5a2HnMSDKEj2GpRa-cw0206","token_type":"Bearer","refresh_token":"1//0hE6s4DovAVfZCgYIARAAGBESNwF-L9IrejP9hGLloqLeV4qTENuLug3NliifxZo2BFdUna-SkE8sNyLn7f-fYriXP2khiLpIzPU","expiry":"2025-12-22T22:01:42.155796716-03:00","expires_in":3599}
team_drive = 

